---
title: Supernormal
timezone: Pacific/Auckland
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hello@garypeters.info
description: Gary Peters makes painting-objects, monochromes, site responsive installations,
  and non-objective wall works.
baseurl: 
url: 
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
